spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: yuan-cam-a
cloud:
  config:
    discovery:
      enabled: true
ribbon:
  eureka:
    enabled: true
eureka:
  client:
    fetch-registry: false
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 10000
#以下配置已写入apollo，在此写入同样生效，但是apollo的配置会覆盖此配置
#test: apollo_test
#spring
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/computer?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    gateway:
#      routes:
#        - id: path_route
#          uri: https://github.com/sunweisheng
#          order: 0
#          predicates:
#            - Path=/test
#          filters:
#            - StripPrefix=1
#server:
#  port: 8762
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    status-page-url: http://127.0.0.1:8762/swagger-ui.html#/